### ISSUE TITLE
Datenbank script

### ISSUE THREAD

**Issue by Bruweiz** [Ilias-fmi/TestOverview#1]
Habe vom Master gebranched, TestOverview funktioniert nichtmehr. Hat wer nen Skript um die Datenbanktabellen die Master haben sollte anzulegen?
[Error.txt](https://github.com/Ilias-fmi/TestOverview/files/699554/Error.txt)

**Comment by st107755** [comment]
Hast du mal probiert TestOverview neu zu installieren, dass das db script neu getriggggggggggert wird
